"""Añadida tabla Concursantes

Revision ID: 1027c3a3cf14
Revises: 2768670819ba
Create Date: 2024-04-24 00:51:43.613113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1027c3a3cf14'
down_revision = '2768670819ba'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concursantes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uq_name', sa.String(length=80), nullable=False),
    sa.Column('uq_descripcion', sa.String(length=200), nullable=False),
    sa.Column('imagen', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uq_descripcion'),
    sa.UniqueConstraint('uq_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('concursantes')
    # ### end Alembic commands ###
