"""Añadida tabla Chef

Revision ID: 2768670819ba
Revises: 5d75671ec444
Create Date: 2024-04-24 00:45:38.314026

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2768670819ba'
down_revision = '5d75671ec444'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chef',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uq_name', sa.String(length=80), nullable=False),
    sa.Column('uq_descripcion', sa.String(length=200), nullable=False),
    sa.Column('imagen', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('uq_descripcion'),
    sa.UniqueConstraint('uq_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chef')
    # ### end Alembic commands ###
