"""Editadas fila surname, password e isactive

Revision ID: e82b66782e16
Revises: 1027c3a3cf14
Create Date: 2024-04-24 02:18:41.307866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e82b66782e16'
down_revision = '1027c3a3cf14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('surname', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('password', sa.String(length=250), nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))
        batch_op.drop_column('uq_username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('uq_username', sa.VARCHAR(length=80), nullable=False))
        batch_op.drop_column('is_active')
        batch_op.drop_column('password')
        batch_op.drop_column('surname')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
